import type { CalendarLibraryFeatures } from './types';

export const calendarLibraries: CalendarLibraryFeatures[] = [
  {
    name: 'React Big Calendar',
    id: 'react-big-calendar',
    description: 'An events calendar component built for React and made for modern browsers.',
    features: {
      dragAndDrop: true,
      multipleViews: true,
      eventCreation: true,
      eventEditing: true,
      eventDeletion: true,
      customStyling: true,
      responsive: true,
      timezone: false,
      recurring: false,
      resourceView: true,
    },
    pros: [
      'Excellent drag and drop support',
      'Multiple view types (month, week, day, agenda)',
      'Good customization options',
      'Active community',
      'Lightweight and performant',
    ],
    cons: [
      'Limited timezone support',
      'No built-in recurring events',
      'Styling can be complex',
      'Learning curve for advanced features',
    ],
    documentation: 'https://jquense.github.io/react-big-calendar/',
    npmPackage: 'react-big-calendar',
  },
  {
    name: 'React Calendar',
    id: 'react-calendar',
    description: 'Ultimate calendar for your React app.',
    features: {
      dragAndDrop: false,
      multipleViews: true,
      eventCreation: false,
      eventEditing: false,
      eventDeletion: false,
      customStyling: true,
      responsive: true,
      timezone: false,
      recurring: false,
      resourceView: false,
    },
    pros: [
      'Simple and lightweight',
      'Great for date picking',
      'Highly customizable styling',
      'Good accessibility support',
      'Easy to integrate',
    ],
    cons: [
      'No event management',
      'Limited functionality for complex calendars',
      'No drag and drop',
      'Basic view options',
    ],
    documentation: 'https://github.com/wojtekmaj/react-calendar',
    npmPackage: 'react-calendar',
  },
  {
    name: 'FullCalendar',
    id: 'fullcalendar',
    description: 'Full-sized drag & drop event calendar for React.',
    features: {
      dragAndDrop: true,
      multipleViews: true,
      eventCreation: true,
      eventEditing: true,
      eventDeletion: true,
      customStyling: true,
      responsive: true,
      timezone: true,
      recurring: true,
      resourceView: true,
    },
    pros: [
      'Most feature-complete solution',
      'Excellent documentation',
      'Strong timezone support',
      'Recurring events support',
      'Professional appearance',
      'Extensive plugin ecosystem',
    ],
    cons: [
      'Larger bundle size',
      'Can be overkill for simple use cases',
      'Steeper learning curve',
      'More complex setup',
    ],
    documentation: 'https://fullcalendar.io/docs/react',
    npmPackage: '@fullcalendar/react',
  },
  {
    name: 'React DatePicker',
    id: 'react-datepicker',
    description: 'A simple and reusable datepicker component for React.',
    features: {
      dragAndDrop: false,
      multipleViews: false,
      eventCreation: false,
      eventEditing: false,
      eventDeletion: false,
      customStyling: true,
      responsive: true,
      timezone: true,
      recurring: false,
      resourceView: false,
    },
    pros: [
      'Excellent for date/time selection',
      'Good timezone support',
      'Highly customizable',
      'Accessible',
      'Well-maintained',
    ],
    cons: [
      'Not a full calendar solution',
      'Limited to date picking',
      'No event management',
      'No calendar views',
    ],
    documentation: 'https://reactdatepicker.com/',
    npmPackage: 'react-datepicker',
  },
]; 